import Head from "next/head";
import { Container } from "@chakra-ui/react";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jorge Contreras Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="100%">
        <Layout>
          <h1>This Works</h1>
        </Layout>
      </Container>
    </>
  );
}
