import Head from "next/head";
import { Container } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jorge Contreras Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container w="100%">
        <h1>This Works</h1>
      </Container>
    </div>
  );
}
